// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPFArchitectureDemo.Data.DatabaseContexts;

#nullable disable

namespace WPFArchitectureDemo.Data.Migrations
{
    [DbContext(typeof(PromptDbContext))]
    partial class PromptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("WPFArchitectureDemo.Domain.Models.Prompt", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("WPFArchitectureDemo.Domain.Models.PromptUsage", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("PromptID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PromptID");

                    b.ToTable("PromptUsages");
                });

            modelBuilder.Entity("WPFArchitectureDemo.Domain.Models.PromptUsage", b =>
                {
                    b.HasOne("WPFArchitectureDemo.Domain.Models.Prompt", "Prompt")
                        .WithMany("PromptUsages")
                        .HasForeignKey("PromptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("WPFArchitectureDemo.Domain.Models.Prompt", b =>
                {
                    b.Navigation("PromptUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
