// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NitasTool
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidNitasToolPackageString = "7405cb6f-0db8-4775-84c8-4bbba386e842";
        public static Guid guidNitasToolPackage = new Guid(guidNitasToolPackageString);

        public const string guidNitasToolPackageCmdSetString = "cd2fada3-6354-43b0-8980-f0eee618e72e";
        public static Guid guidNitasToolPackageCmdSet = new Guid(guidNitasToolPackageCmdSetString);

        public const string guidImagesString = "c8c61e19-bc4f-414c-a6fd-0c2ca814a9d5";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int cmdidToolWindow1Command = 0x1021;
        public const int bmpPic1 = 0x0001;
    }
}